name: nsca
on: [push]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  run_nscloud_action:
    runs-on: ubuntu-latest
    name: Deploy a sample application to Namespace Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: namespacelabs/nscloud-action@v0.0.1
      - name: Apply configurations
        run: |
          kubectl apply -f testdata/kubernetes/demo.yaml
      - name: Wait until Redis is available
        run: |
          kubectl wait deployment -n demo-app demo-redis-server --for condition=Available=True --timeout=90s
      - name: Check result
        run: |
          kubectl get all -A
